[GLOBAL]
pants_version = "2.11.0"
pythonpath = ["%(buildroot)s/pants-plugins"]
backend_packages = [
    "pants.backend.docker",
    "pants.backend.docker.lint.hadolint",
    "pants.backend.python",
    "pants.backend.experimental.python",
    "pants.backend.python.lint.black",
    "pants.backend.python.typecheck.mypy",
    "pants.backend.python.lint.docformatter",
    "python_plugins.setup_py",
]


[source]
root_patterns = ["/"]

[test]
extra_env_vars = ["CODEARTIFACT_AUTH_TOKEN"]


[anonymous-telemetry]
enabled = false

[python]
tailor_ignore_solitary_init_files = false
interpreter_constraints = ["==3.10.*"]

[python-infer]
inits = true

[python-bootstrap]
search_path = ["<PATH>", "<PYENV>", "/opt/python3"]

[docker]
build_args = ["CONDAENV=fundl", "PACKAGE_VERSION"]
[docker.registries.smiletronix]
address = "483380410959.dkr.ecr.us-east-1.amazonaws.com"
default = true
